#!/bin/bash

echo -e "Quel utilisateur souhaitez vous logout ?" && who

ret=pkill -KILL -u $1

if [$ret -eq 1]; then
	echo -e "Souhaitez-vous également supprimer l utilisateur ?\\ny/N\\n"
	read answ
	if [ answ = "y" || answ = "yes"]; then
		sudo userdel $1
	fi
fi
